version: 0.2
phases:
  pre-build:
    commands:
      - python -m pip install -U pip
  build:
    commands:
      - ./create_deployment_package.sh
artifacts:
  files:
    - '**/*'
  name: myname-$AWS_REGION 
