version: 0.2
phases:
  pre_build:
    commands:
      - uname -a
      - apt install python3-pip      
  build:
    commands:
      - ./create_deployment_package.sh
artifacts:
  files:
    - '**/*'
  name: myname-$AWS_REGION 
