version: 0.2
phases:
  pre_build:
    commands:
      - uname -a 
      - mvn -version  
  build:
    commands:
      - ./create_deployment_package.sh
      - aws s3 cp codebuild-ci-lambda.zip s3://bucket-name-for-lambda-3/
artifacts:
  files:
    - '**/*'
  name: myname-$AWS_REGION 
